// Package main demonstrates how to use proto2mcp-generated code.
//
// In a real project, the handler interface and RegisterXxxMCP function
// would be generated by protoc-gen-proto2mcp. Here we simulate them
// to show the developer experience.
package main

import (
	"context"
	"encoding/json"
	"log"

	"github.com/protocgen/proto2mcp/pkg/mcpruntime"
)

// --- Simulated generated types (in real usage, these come from protoc) ---

type GetPatientRequest struct{ PatientId string `json:"patient_id"` }
type GetPatientResponse struct{ PatientId string `json:"patient_id"` }
type ListPatientsRequest struct{ Limit int32 `json:"limit"` }
type ListPatientsResponse struct{}
type CreateAppointmentRequest struct {
	PatientId string `json:"patient_id"`
	DoctorId  string `json:"doctor_id"`
}
type CreateAppointmentResponse struct{ AppointmentId string `json:"appointment_id"` }

// --- Simulated generated handler interface ---

// PatientServiceMCPHandler is the interface generated by protoc-gen-proto2mcp.
// Users implement this with their business logic.
type PatientServiceMCPHandler interface {
	GetPatient(ctx context.Context, req *GetPatientRequest) (*GetPatientResponse, error)
	ListPatients(ctx context.Context, req *ListPatientsRequest) (*ListPatientsResponse, error)
	CreateAppointment(ctx context.Context, req *CreateAppointmentRequest) (*CreateAppointmentResponse, error)
}

// --- Simulated generated registration function ---

// RegisterPatientServiceMCP registers all MCP tools for PatientService.
// In real usage, this function is generated by protoc-gen-proto2mcp.
func RegisterPatientServiceMCP(registry *mcpruntime.ToolRegistry, handler PatientServiceMCPHandler, opts ...mcpruntime.Option) {
	cfg := mcpruntime.NewConfig(opts...)

	// Tool: GetPatient
	registry.Register(
		mcpruntime.ToolDefinition{
			Name:        "PatientService_GetPatient",
			Description: "Look up a patient record by ID",
			InputSchema: json.RawMessage(`{"type":"object","properties":{"patient_id":{"type":"string","minLength":1}},"required":["patient_id"]}`),
		},
		cfg.WrapHandler("PatientService_GetPatient", func(ctx context.Context, req mcpruntime.ToolRequest) (*mcpruntime.CallToolResult, error) {
			var input GetPatientRequest
			if err := json.Unmarshal(req.Arguments, &input); err != nil {
				return mcpruntime.InvalidParamsError(err), nil
			}
			resp, err := handler.GetPatient(ctx, &input)
			if err != nil {
				return mcpruntime.MapConnectError(err), nil
			}
			b, _ := json.Marshal(resp)
			return &mcpruntime.CallToolResult{Content: b}, nil
		}),
	)

	// Tool: ListPatients
	registry.Register(
		mcpruntime.ToolDefinition{
			Name:        "PatientService_ListPatients",
			Description: "List multiple patients",
			InputSchema: json.RawMessage(`{"type":"object","properties":{"limit":{"type":"integer"}}}`),
		},
		cfg.WrapHandler("PatientService_ListPatients", func(ctx context.Context, req mcpruntime.ToolRequest) (*mcpruntime.CallToolResult, error) {
			var input ListPatientsRequest
			if err := json.Unmarshal(req.Arguments, &input); err != nil {
				return mcpruntime.InvalidParamsError(err), nil
			}
			resp, err := handler.ListPatients(ctx, &input)
			if err != nil {
				return mcpruntime.MapConnectError(err), nil
			}
			b, _ := json.Marshal(resp)
			return &mcpruntime.CallToolResult{Content: b}, nil
		}),
	)

	// Tool: CreateAppointment
	registry.Register(
		mcpruntime.ToolDefinition{
			Name:        "PatientService_CreateAppointment",
			Description: "Schedule a new appointment for an existing patient",
			InputSchema: json.RawMessage(`{"type":"object","properties":{"patient_id":{"type":"string"},"doctor_id":{"type":"string"}}}`),
		},
		cfg.WrapHandler("PatientService_CreateAppointment", func(ctx context.Context, req mcpruntime.ToolRequest) (*mcpruntime.CallToolResult, error) {
			var input CreateAppointmentRequest
			if err := json.Unmarshal(req.Arguments, &input); err != nil {
				return mcpruntime.InvalidParamsError(err), nil
			}
			resp, err := handler.CreateAppointment(ctx, &input)
			if err != nil {
				return mcpruntime.MapConnectError(err), nil
			}
			b, _ := json.Marshal(resp)
			return &mcpruntime.CallToolResult{Content: b}, nil
		}),
	)
}

// --- User's implementation ---

type myHandler struct{}

func (h *myHandler) GetPatient(_ context.Context, req *GetPatientRequest) (*GetPatientResponse, error) {
	log.Printf("GetPatient called for %s", req.PatientId)
	return &GetPatientResponse{PatientId: req.PatientId}, nil
}

func (h *myHandler) ListPatients(_ context.Context, req *ListPatientsRequest) (*ListPatientsResponse, error) {
	log.Printf("ListPatients called with limit %d", req.Limit)
	return &ListPatientsResponse{}, nil
}

func (h *myHandler) CreateAppointment(_ context.Context, req *CreateAppointmentRequest) (*CreateAppointmentResponse, error) {
	log.Printf("CreateAppointment called for patient %s", req.PatientId)
	return &CreateAppointmentResponse{AppointmentId: "appt-123"}, nil
}

func main() {
	// 1. Create a tool registry.
	registry := mcpruntime.NewToolRegistry()

	// 2. Implement the handler.
	handler := &myHandler{}

	// 3. Register MCP tools (this is generated code in real usage).
	RegisterPatientServiceMCP(registry, handler)

	// 4. Print registered tools.
	log.Printf("Registered %d tools:", len(registry.Tools()))
	for _, tool := range registry.Tools() {
		log.Printf("  - %s: %s", tool.Name, tool.Description)
	}

	// In production, you'd hook registry into an MCP transport (stdio, SSE, etc.)
	log.Println("MCP server ready.")
}
