package emit

import (
	"github.com/dave/jennifer/jen"
	"github.com/protocgen/proto2mcp/codegen/pkg/extract"
)

const (
	// runtimePkg is the import path for the mcpruntime package.
	runtimePkg = "github.com/protocgen/proto2mcp/pkg/mcpruntime"
	// connectBridgePkg is the import path for the connectbridge package.
	connectBridgePkg = "github.com/protocgen/proto2mcp/pkg/mcpruntime/connectbridge"
	// connectPkg is the import path for ConnectRPC.
	connectPkg = "connectrpc.com/connect"
)

// TypeRef holds a Go type reference for code generation.
type TypeRef struct {
	ImportPath string // e.g., "github.com/myapp/gen/myapp/v1"
	TypeName   string // e.g., "GetPatientRequest"
}

// ToolEmitInfo holds the information needed to emit code for a single tool.
type ToolEmitInfo struct {
	Tool       extract.ToolIR
	InputType  TypeRef
	OutputType TypeRef
}

// ServiceEmitInfo holds everything needed to emit code for a service.
type ServiceEmitInfo struct {
	Service         extract.ServiceIR
	Tools           []ToolEmitInfo
	GoPackage       string // Go package name for the output file
	GoImportPath    string // Go import path for the output file
	GenerateConnect bool   // If true, generate ConnectRPC forwarding
	// ConnectClientType is the name of the ConnectRPC client interface.
	// If empty, defaults to ServiceName + "ServiceClient".
	ConnectClientType string
}

// GenerateFile produces a jennifer File for the given service IRs.
// All services should belong to the same package.
// The generated file contains:
// - Handler interface for the service
// - Registration function that wires tools to the MCP server
// - Tool definition constants (names, descriptions, schemas)
func GenerateFile(infos []ServiceEmitInfo) *jen.File {
	var pkgPath string
	if len(infos) > 0 {
		pkgPath = infos[0].GoImportPath
	} else {
		pkgPath = "generated"
	}
	f := jen.NewFilePath(pkgPath)
	f.PackageComment("Code generated by protoc-gen-proto2mcp. DO NOT EDIT.")

	for _, info := range infos {
		generateHandlerInterface(f, info)
		generateToolDefinitions(f, info)
		generateRegisterFunc(f, info)

		if info.GenerateConnect {
			generateConnectForwarder(f, info)
		}
	}

	return f
}

// generateToolDefinitions generates tool name, description, and schema constants.
func generateToolDefinitions(f *jen.File, info ServiceEmitInfo) {
	for _, t := range info.Tools {
		nameConst := t.Tool.Name + "Name"
		descConst := t.Tool.Name + "Description"
		schemaConst := t.Tool.Name + "Schema"

		f.Const().Id(nameConst).Op("=").Lit(t.Tool.Name)
		f.Const().Id(descConst).Op("=").Lit(t.Tool.Description)

		f.Var().Id(schemaConst).Op("=").Index().Byte().Call(jen.Lit(string(t.Tool.InputSchema)))
	}
}
