package extract_test

import (
	"strings"
	"testing"

	"github.com/protocgen/proto2mcp/codegen/pkg/emit"
	"github.com/protocgen/proto2mcp/codegen/pkg/extract"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/descriptorpb"
)

// ============================================================================
// End-to-End: Extract → Emit → Render
// ============================================================================

func TestE2E_ExtractToEmitRoundtrip(t *testing.T) {
	fd := &descriptorpb.FileDescriptorProto{
		Name:    strPtr("test/v1/e2e.proto"),
		Package: strPtr("test.v1"),
		Syntax:  strPtr("proto3"),
		Options: &descriptorpb.FileOptions{
			GoPackage: strPtr("github.com/test/v1;testv1"),
		},
		EnumType: []*descriptorpb.EnumDescriptorProto{
			{
				Name: strPtr("Priority"),
				Value: []*descriptorpb.EnumValueDescriptorProto{
					{Name: strPtr("PRIORITY_UNSPECIFIED"), Number: int32Ptr(0)},
					{Name: strPtr("PRIORITY_HIGH"), Number: int32Ptr(1)},
					{Name: strPtr("PRIORITY_LOW"), Number: int32Ptr(2)},
				},
			},
		},
		MessageType: []*descriptorpb.DescriptorProto{
			{
				Name: strPtr("CreateTaskRequest"),
				Field: []*descriptorpb.FieldDescriptorProto{
					makeField("title", 1, descriptorpb.FieldDescriptorProto_TYPE_STRING),
					makeField("description", 2, descriptorpb.FieldDescriptorProto_TYPE_STRING),
					{
						Name: strPtr("priority"), Number: int32Ptr(3),
						Label: labelPtr(descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL),
						Type: typePtr(descriptorpb.FieldDescriptorProto_TYPE_ENUM),
						TypeName: strPtr(".test.v1.Priority"), JsonName: strPtr("priority"),
					},
					{
						Name: strPtr("tags"), Number: int32Ptr(4),
						Label: labelPtr(descriptorpb.FieldDescriptorProto_LABEL_REPEATED),
						Type: typePtr(descriptorpb.FieldDescriptorProto_TYPE_STRING),
						JsonName: strPtr("tags"),
					},
				},
			},
			makeSimpleMessage("CreateTaskResponse",
				makeField("task_id", 1, descriptorpb.FieldDescriptorProto_TYPE_STRING),
			),
			makeSimpleMessage("GetTaskRequest",
				makeField("task_id", 1, descriptorpb.FieldDescriptorProto_TYPE_STRING),
			),
			makeSimpleMessage("GetTaskResponse",
				makeField("title", 1, descriptorpb.FieldDescriptorProto_TYPE_STRING),
				makeField("done", 2, descriptorpb.FieldDescriptorProto_TYPE_BOOL),
			),
		},
		Service: []*descriptorpb.ServiceDescriptorProto{
			{
				Name: strPtr("TaskService"),
				Method: []*descriptorpb.MethodDescriptorProto{
					makeMethod("CreateTask", ".test.v1.CreateTaskRequest", ".test.v1.CreateTaskResponse"),
					makeMethod("GetTask", ".test.v1.GetTaskRequest", ".test.v1.GetTaskResponse"),
				},
			},
		},
	}

	plugin := buildPlugin(t, fd)

	// Step 1: Extract
	results, err := extract.FromPlugin(plugin)
	if err != nil {
		t.Fatalf("FromPlugin failed: %v", err)
	}
	if len(results) != 1 {
		t.Fatalf("expected 1 FileIR, got %d", len(results))
	}

	fileIR := results[0]
	if len(fileIR.Services) != 1 {
		t.Fatalf("expected 1 service, got %d", len(fileIR.Services))
	}

	svcIR := fileIR.Services[0]
	if len(svcIR.Tools) != 2 {
		t.Fatalf("expected 2 tools, got %d", len(svcIR.Tools))
	}

	// Step 2: Build ServiceEmitInfo (same as main.go does)
	protoFile := plugin.FilesByPath["test/v1/e2e.proto"]
	protoSvc := protoFile.Services[0]

	methodMap := make(map[string]int)
	for i, m := range protoSvc.Methods {
		methodMap[string(m.Desc.Name())] = i
	}

	var toolInfos []emit.ToolEmitInfo
	for _, toolIR := range svcIR.Tools {
		idx := methodMap[toolIR.MethodName]
		m := protoSvc.Methods[idx]
		toolInfos = append(toolInfos, emit.ToolEmitInfo{
			Tool: toolIR,
			InputType: emit.TypeRef{
				ImportPath: string(m.Input.GoIdent.GoImportPath),
				TypeName:   m.Input.GoIdent.GoName,
			},
			OutputType: emit.TypeRef{
				ImportPath: string(m.Output.GoIdent.GoImportPath),
				TypeName:   m.Output.GoIdent.GoName,
			},
		})
	}

	info := emit.ServiceEmitInfo{
		Service:      svcIR,
		Tools:        toolInfos,
		GoPackage:    string(protoFile.GoPackageName),
		GoImportPath: string(protoFile.GoImportPath),
	}

	// Step 3: Generate code
	jFile := emit.GenerateFile([]emit.ServiceEmitInfo{info})

	// Step 4: Render to string
	var buf strings.Builder
	if err := jFile.Render(&buf); err != nil {
		t.Fatalf("Render failed: %v", err)
	}

	output := buf.String()
	if len(output) == 0 {
		t.Fatal("expected non-empty generated output")
	}

	// Verify generated code structure
	if !strings.Contains(output, "Code generated by protoc-gen-proto2mcp") {
		t.Error("expected generated code header comment")
	}
	if !strings.Contains(output, "TaskServiceMCPHandler") {
		t.Error("expected handler interface 'TaskServiceMCPHandler'")
	}
	if !strings.Contains(output, "RegisterTaskServiceMCP") {
		t.Error("expected registration function 'RegisterTaskServiceMCP'")
	}
	if !strings.Contains(output, "TaskService_CreateTask") {
		t.Error("expected tool name 'TaskService_CreateTask'")
	}
	if !strings.Contains(output, "TaskService_GetTask") {
		t.Error("expected tool name 'TaskService_GetTask'")
	}

	// Verify it imports the runtime package
	if !strings.Contains(output, "mcpruntime") {
		t.Error("expected import of mcpruntime package")
	}

	// Verify schema is embedded (as json.RawMessage literal)
	if !strings.Contains(output, "InputSchema") {
		t.Error("expected InputSchema reference in generated code")
	}

	t.Logf("Generated %d bytes of Go code", len(output))
}

func TestE2E_ExtractToEmit_MultiService(t *testing.T) {
	fd := &descriptorpb.FileDescriptorProto{
		Name:    strPtr("test/v1/multi_e2e.proto"),
		Package: strPtr("test.v1"),
		Syntax:  strPtr("proto3"),
		Options: &descriptorpb.FileOptions{
			GoPackage: strPtr("github.com/test/v1;testv1"),
		},
		MessageType: []*descriptorpb.DescriptorProto{
			makeSimpleMessage("ReqA", makeField("a", 1, descriptorpb.FieldDescriptorProto_TYPE_STRING)),
			makeSimpleMessage("RespA", makeField("a", 1, descriptorpb.FieldDescriptorProto_TYPE_STRING)),
			makeSimpleMessage("ReqB", makeField("b", 1, descriptorpb.FieldDescriptorProto_TYPE_INT32)),
			makeSimpleMessage("RespB", makeField("b", 1, descriptorpb.FieldDescriptorProto_TYPE_INT32)),
		},
		Service: []*descriptorpb.ServiceDescriptorProto{
			{
				Name: strPtr("AlphaService"),
				Method: []*descriptorpb.MethodDescriptorProto{
					makeMethod("AlphaMethod", ".test.v1.ReqA", ".test.v1.RespA"),
				},
			},
			{
				Name: strPtr("BetaService"),
				Method: []*descriptorpb.MethodDescriptorProto{
					makeMethod("BetaMethod", ".test.v1.ReqB", ".test.v1.RespB"),
				},
			},
		},
	}

	plugin := buildPlugin(t, fd)
	results, err := extract.FromPlugin(plugin)
	if err != nil {
		t.Fatalf("FromPlugin failed: %v", err)
	}

	protoFile := plugin.FilesByPath["test/v1/multi_e2e.proto"]

	var infos []emit.ServiceEmitInfo
	for _, svcIR := range results[0].Services {
		var protoSvc *protogen.Service
		for _, s := range protoFile.Services {
			if string(s.Desc.FullName()) == svcIR.FullName {
				protoSvc = s
				break
			}
		}

		methodMap := make(map[string]int)
		for i, m := range protoSvc.Methods {
			methodMap[string(m.Desc.Name())] = i
		}

		var toolInfos []emit.ToolEmitInfo
		for _, toolIR := range svcIR.Tools {
			idx := methodMap[toolIR.MethodName]
			m := protoSvc.Methods[idx]
			toolInfos = append(toolInfos, emit.ToolEmitInfo{
				Tool: toolIR,
				InputType: emit.TypeRef{
					ImportPath: string(m.Input.GoIdent.GoImportPath),
					TypeName:   m.Input.GoIdent.GoName,
				},
				OutputType: emit.TypeRef{
					ImportPath: string(m.Output.GoIdent.GoImportPath),
					TypeName:   m.Output.GoIdent.GoName,
				},
			})
		}

		infos = append(infos, emit.ServiceEmitInfo{
			Service:      svcIR,
			Tools:        toolInfos,
			GoPackage:    string(protoFile.GoPackageName),
			GoImportPath: string(protoFile.GoImportPath),
		})
	}

	jFile := emit.GenerateFile(infos)

	var buf strings.Builder
	if err := jFile.Render(&buf); err != nil {
		t.Fatalf("Render failed: %v", err)
	}

	output := buf.String()

	// Both service handlers should exist
	if !strings.Contains(output, "AlphaServiceMCPHandler") {
		t.Error("expected AlphaServiceMCPHandler")
	}
	if !strings.Contains(output, "BetaServiceMCPHandler") {
		t.Error("expected BetaServiceMCPHandler")
	}
	if !strings.Contains(output, "RegisterAlphaServiceMCP") {
		t.Error("expected RegisterAlphaServiceMCP")
	}
	if !strings.Contains(output, "RegisterBetaServiceMCP") {
		t.Error("expected RegisterBetaServiceMCP")
	}
}
